### ISSUE TITLE
DataManager' object has no attribute 'get_total_classnum

### ISSUE THREAD

**Issue by weiwei11** [G-U-N/PyCIL#12]
Hello, you did an excellent job and thanks for your contribution.
But I meet `AttributeError: 'DataManager' object has no attribute 'get_total_classnum'` when run `python main.py --config=./exps/coil.json`. Here are the details:
```
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    main()
  File "main.py", line 12, in main
    train(args)
  File "/root/weiwei/PyCIL/trainer.py", line 18, in train
    _train(args)
  File "/root/weiwei/PyCIL/trainer.py", line 50, in _train
    model.after_task()
  File "/root/weiwei/PyCIL/models/coil.py", line 38, in after_task
    self.nextperiod_initialization=self.solving_ot()
  File "/root/weiwei/PyCIL/models/coil.py", line 45, in solving_ot
    if self._total_classes==self.data_manager.get_total_classnum():
AttributeError: 'DataManager' object has no attribute 'get_total_classnum'
```

**Comment by weiwei11** [comment]
I fixed the problem by add the code to `DataManager`:
```python
    def get_total_classnum(self):
        return len(self._class_order)
```
And the code above is from [https://github.com/zhoudw-zdw/MM21-Coil/blob/main/utils/data_manager.py](https://github.com/zhoudw-zdw/MM21-Coil/blob/main/utils/data_manager.py)

**Comment by zhoudw-zdw** [comment]
Fixed, thx!
