### ISSUE TITLE
foster error: TypeError: string indices must be integers

### ISSUE THREAD

**Issue by muyuuuu** [G-U-N/PyCIL#23]
after train the second task and before compress:

```
Task 1, Epoch 167/170 => Loss 0.752, Loss_clf 0.000, Loss_fe 0.001, Loss_kd 0.375, Train_accy 99.00:  98%|█████████▊| 167/170 [09:02<00:10,  3.35s/it]
Task 1, Epoch 168/170 => Loss 0.746, Loss_clf 0.001, Loss_fe 0.001, Loss_kd 0.372, Train_accy 98.75:  98%|█████████▊| 167/170 [09:04<00:10,  3.35s/it]
Task 1, Epoch 168/170 => Loss 0.746, Loss_clf 0.001, Loss_fe 0.001, Loss_kd 0.372, Train_accy 98.75:  99%|█████████▉| 168/170 [09:04<00:06,  3.20s/it]
Task 1, Epoch 169/170 => Loss 0.744, Loss_clf 0.001, Loss_fe 0.001, Loss_kd 0.371, Train_accy 98.81:  99%|█████████▉| 168/170 [09:07<00:06,  3.20s/it]
Task 1, Epoch 169/170 => Loss 0.744, Loss_clf 0.001, Loss_fe 0.001, Loss_kd 0.371, Train_accy 98.81:  99%|█████████▉| 169/170 [09:07<00:03,  3.10s/it]
Task 1, Epoch 170/170 => Loss 0.746, Loss_clf 0.001, Loss_fe 0.001, Loss_kd 0.372, Train_accy 98.67:  99%|█████████▉| 169/170 [09:10<00:03,  3.10s/it]
Task 1, Epoch 170/170 => Loss 0.746, Loss_clf 0.001, Loss_fe 0.001, Loss_kd 0.372, Train_accy 98.67: 100%|██████████| 170/170 [09:10<00:00,  3.01s/it]
Task 1, Epoch 170/170 => Loss 0.746, Loss_clf 0.001, Loss_fe 0.001, Loss_kd 0.372, Train_accy 98.67: 100%|██████████| 170/170 [09:10<00:00,  3.24s/it]
Traceback (most recent call last):
  File "foster.py", line 31, in <module>
    main()
  File "foster.py", line 12, in main
    train(args)
  File "/home/20031211496/Documents/PYCIL/PyCIL-master/trainer.py", line 18, in train
    _train(args)
  File "/home/20031211496/Documents/PYCIL/PyCIL-master/trainer.py", line 67, in _train
    model.incremental_train(data_manager)
  File "/home/20031211496/Documents/PYCIL/PyCIL-master/models/foster.py", line 89, in incremental_train
    self._train(self.train_loader, self.test_loader)
  File "/home/20031211496/Documents/PYCIL/PyCIL-master/models/foster.py", line 169, in _train
    self._feature_compression(train_loader, test_loader)
  File "/home/20031211496/Documents/PYCIL/PyCIL-master/models/foster.py", line 289, in _feature_compression
    self._snet = FOSTERNet(self.args["convnet_type"], False)
  File "/home/20031211496/Documents/PYCIL/PyCIL-master/utils/inc_net.py", line 402, in __init__
    self.convnet_type = args["convnet_type"]
TypeError: string indices must be integers
```

**Comment by muyuuuu** [comment]
configs:

```
{
    "prefix": "cil",
    "dataset": "cifar100",
    "memory_size": 2000,
    "memory_per_class": 20,
    "fixed_memory": true,
    "shuffle": true,
    "init_cls": 10,
    "increment": 10,
    "model_name": "foster",
    "convnet_type": "resnet18",
    "device": ["0"],
    "seed": [1993],
    "beta1":0.96,
    "beta2":0.97,
    "oofc":"ft",
    "is_teacher_wa":false,
    "is_student_wa":false,
    "lambda_okd":1,
    "wa_value":1,
    "init_epochs": 200,
    "init_lr" : 0.1,
    "init_weight_decay" : 0,
    "boosting_epochs" : 170,
    "compression_epochs" : 130,
    "lr" : 0.1,
    "batch_size" : 128,
    "weight_decay" : 0,
    "num_workers" : 8,
    "T" : 2
}
```

**Comment by G-U-N** [comment]
Thanks. I have solved the bug.

And refer to this [repo](https://github.com/G-U-N/ECCV22-FOSTER) to reproduce ideal results.
