### ISSUE TITLE
Fetril gets error on cifar10

### ISSUE THREAD

**Issue by valeriya-khan** [G-U-N/PyCIL#35]
Hi! I saw the same issue that was closed. However, I got it now. How can I resolve it?
**Config:**
{
    "prefix": "train",
    "dataset": "clipart",
    "memory_size": 0,
    "shuffle": true,
    "init_cls": 40,
    "increment": 1,
    "model_name": "fetril",
    "convnet_type": "resnet32",
    "device": ["0"],
    "seed": [1993],
    "init_epochs": 200,
    "init_lr" : 0.1,
    "init_weight_decay" : 5e-4,
    "epochs" : 50,
    "lr" : 0.05,
    "batch_size" : 128,
    "weight_decay" : 5e-4,
    "num_workers" : 8,
    "T" : 2
}
**The error:**
  0%|                                                                                                          | 0/200 [00:00<?, ?it/s]
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/khan_lera/miniconda3/envs/contle/lib/python3.10/site-packages/humbug/report.py", line 525, in _hook
    self.error_report(error=exception_instance, tags=tags, publish=publish)
  File "/home/khan_lera/miniconda3/envs/contle/lib/python3.10/site-packages/humbug/report.py", line 267, in error_report
    traceback.format_exception(
TypeError: format_exception() got an unexpected keyword argument 'etype'

Original exception was:
Traceback (most recent call last):
  File "/home/khan_lera/pycil/main.py", line 31, in <module>
    main()
  File "/home/khan_lera/pycil/main.py", line 12, in main
    train(args)
  File "/home/khan_lera/pycil/trainer.py", line 18, in train
    _train(args)
  File "/home/khan_lera/pycil/trainer.py", line 65, in _train
    model.incremental_train(data_manager)
  File "/home/khan_lera/pycil/models/fetril.py", line 86, in incremental_train
    self._train(self.train_loader, self.test_loader)
  File "/home/khan_lera/pycil/models/fetril.py", line 102, in _train
    self._train_function(train_loader, test_loader, optimizer, scheduler)
  File "/home/khan_lera/pycil/models/fetril.py", line 175, in _train_function
    for i, (_, inputs, targets) in enumerate(train_loader):
  File "/home/khan_lera/miniconda3/envs/contle/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/khan_lera/miniconda3/envs/contle/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/home/khan_lera/miniconda3/envs/contle/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/home/khan_lera/miniconda3/envs/contle/lib/python3.10/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/khan_lera/miniconda3/envs/contle/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/khan_lera/miniconda3/envs/contle/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/khan_lera/miniconda3/envs/contle/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/khan_lera/pycil/utils/data_manager.py", line 202, in __getitem__
    image = self.trsf(pil_loader(self.images[idx]))
  File "/home/khan_lera/miniconda3/envs/contle/lib/python3.10/site-packages/torchvision/transforms/transforms.py", line 94, in __call__
    img = t(img)
  File "/home/khan_lera/miniconda3/envs/contle/lib/python3.10/site-packages/torchvision/transforms/transforms.py", line 134, in __call__
    return F.to_tensor(pic)
  File "/home/khan_lera/miniconda3/envs/contle/lib/python3.10/site-packages/torchvision/transforms/functional.py", line 138, in to_tensor
    raise TypeError(f"pic should be PIL Image or ndarray. Got {type(pic)}")
TypeError: pic should be PIL Image or ndarray. Got <class 'torch.Tensor'>

**Comment by G-U-N** [comment]
This error indicates that you have tried to transform an Image with transforms.ToTensor() twice. 
Add the following lines to check whether your train/test_trsf conflicts with the common_trsf.
```
print(self.data_manager._train_trsf)
print(self.data_manager._test_trsf) 
print(self.data_manager._common_trsf)
```

**Comment by valeriya-khan** [comment]
It works now, thanks!
