### ISSUE TITLE
The following error occurs when training SSRE

### ISSUE THREAD

**Issue by Fenghao1995** [G-U-N/PyCIL#38]
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    main()
  File "main.py", line 12, in main
    train(args)
  File "/home/isalab203/code/FH_IL/PyCIL-master/trainer.py", line 28, in train
    _train(args)
  File "/home/isalab203/code/FH_IL/PyCIL-master/trainer.py", line 75, in _train
    model.incremental_train(data_manager)
  File "/home/isalab203/code/FH_IL/PyCIL-master/models/ssre.py", line 62, in incremental_train
    self._network_expansion()    
  File "/home/isalab203/code/FH_IL/PyCIL-master/models/ssre.py", line 238, in _network_expansion
    self._network.convnet.switch("parallel_adapters")
  File "/home/isalab203/.conda/envs/CIL/lib/python3.8/site-packages/torch/nn/modules/module.py", line 947, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'CifarResNet' object has no attribute 'switch'
#####################################
It seems that inc_net.py lacks the switch method？

**Comment by G-U-N** [comment]
Thanks for your interest. You should use `resnet18_rep` (modified_represnet) instead of `resnet32` (cifar_resnet) for experiments on SSRE.

**Comment by Fenghao1995** [comment]
Thank you. It works fine.
