### ISSUE TITLE
当我运行fetril方法，使用ImageNet数据集，data_manager.py报错

### ISSUE THREAD

**Issue by junkdog-joe** [G-U-N/PyCIL#73]
File "E:\PYCIL\PyCIL\utils\data_manager.py", line 260, in __getitem__
    image = self.trsf(pil_loader(self.images[idx]))
    img = t(img)
TypeError: 'str' object is not callable

像这样trsf函数被认为是str

**Comment by G-U-N** [comment]
Could you please provide more detailed error logs?

**Comment by junkdog-joe** [comment]
> Could you please provide more detailed error logs?

Traceback (most recent call last):
  File "E:\PYCIL\PyCIL\main.py", line 34, in <module>
    main()
  File "E:\PYCIL\PyCIL\main.py", line 15, in main
    train(args)
  File "E:\PYCIL\PyCIL\trainer.py", line 18, in train
    _train(args)
  File "E:\PYCIL\PyCIL\trainer.py", line 67, in _train
    model.incremental_train(data_manager)
  File "E:\PYCIL\PyCIL\models\fetril.py", line 90, in incremental_train
    self._train(self.train_loader, self.test_loader)
  File "E:\PYCIL\PyCIL\models\fetril.py", line 106, in _train
    self._train_function(train_loader, test_loader, optimizer, scheduler)
  File "E:\PYCIL\PyCIL\models\fetril.py", line 179, in _train_function
    for i, (_, inputs, targets) in enumerate(train_loader):
  File "C:\Users\86189\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "C:\Users\86189\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "C:\Users\86189\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 1402, in _process_data
    data.reraise()
  File "C:\Users\86189\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\_utils.py", line 461, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\86189\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\86189\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\86189\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\PYCIL\PyCIL\utils\data_manager.py", line 260, in __getitem__
    image = self.trsf(pil_loader(self.images[idx]))
  File "C:\Users\86189\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\transforms\transforms.py", line 94, in __call__
    img = t(img)
TypeError: 'str' object is not callable

**Comment by G-U-N** [comment]
I think deleting this [line](https://github.com/G-U-N/PyCIL/blob/master/models/fetril.py#L50) should probably work. LMK if you fix it.

**Comment by junkdog-joe** [comment]
> 我认为删除这一[行](https://github.com/G-U-N/PyCIL/blob/master/models/fetril.py#L50)应该可行。 LMK 如果你修复它。

十分感谢！我修复了这个错误

**Comment by G-U-N** [comment]
Great. Glad to help you with that.
